version: '3'

services:
    backend:
        image: 'chat_app_backend'
        container_name: "nodejs_server"
        build:
            context: ./backend
        volumes:
            - ./backend/:/server/
            - /server/node_modules
        env_file: .env
        environment:
            PORT: 5001
        links:
            - mongodb
        depends_on:
            - mongodb
        ports:
            - 5001:5001

    app:
        image: 'chatapp_app'
        container_name: "react_app"
        build:
            context: ./app
        volumes:
            - ./app:/app
            - /app/node_modules
        env_file: .env
        ports:
            - 3000:3000

    mongodb:
        image: mongo:4.0
        container_name: "mongodb"
        restart: always
        env_file: .env
        volumes:
            - ./data:/data/db
        ports:
            - 27017:27017
